//
// Created by DaveRiedel on 13-Jun-22.
//

#ifndef BITSANDDROIDSCONNECTOR_CURVETYPEENUM_H
#define BITSANDDROIDSCONNECTOR_CURVETYPEENUM_H
static enum CurveTypeEnum {
    RUDDER,
    LEFTBRAKE,
    RIGHTBRAKE,
    AILERON,
    ELEVATOR
} types;
#endif //BITSANDDROIDSCONNECTOR_CURVETYPEENUM_H
