#ifndef INPUTENUM_H
#define INPUTENUM_H

class InputEnum {
public:
    InputEnum();

    enum DATA_DEFINE_ID_INPUT {
        // Engine
        DATA_THROTTLE_1_AXIS,
        DATA_THROTTLE_2_AXIS,
        DATA_THROTTLE_3_AXIS,
        DATA_THROTTLE_4_AXIS,
        DATA_EX_THROTTLE_1_AXIS,
        DATA_EX_THROTTLE_2_AXIS,
        DATA_EX_THROTTLE_3_AXIS,
        DATA_EX_THROTTLE_4_AXIS,
        DEFINITION_THROTTLE_1,
        DEFINITION_THROTTLE_2,
        DEFINITION_THROTTLE_3,
        DEFINITION_THROTTLE_4,
        DEFINITION_MIXTURE_1,
        DEFINITION_PROPELLER_LEVER_POSITION_1,
        DEFINITION_PROPELLER_LEVER_POSITION_2,
        DEFINITION_PROP_LEVER_AXIS_1,
        DEFINITION_PROP_LEVER_AXIS_2,
        DEFINITION_PROP_LEVER_AXIS_3,
        DEFINITION_PROP_LEVER_AXIS_4,
        DEFINITION_MIXTURE_LEVER_AXIS_1,
        DEFINITION_MIXTURE_LEVER_AXIS_2,
        DEFINITION_MIXTURE_LEVER_AXIS_3,
        DEFINITION_MIXTURE_LEVER_AXIS_4,

        DEFINITION_AXIS_FLAPS_SET,

        DEFINITION_AXIS_RUDDER_SET,
        DEFINITION_AXIS_RIGHT_BRAKE_SET,
        DEFINITION_AXIS_LEFT_BRAKE_SET,

        DEFINITION_AXIS_ELEVATOR_SET,
        DEFINITION_AXIS_AILERONS_SET,
        DEFINITION_ELEVATOR_TRIM_SET
    };
};

#endif  // INPUTENUM_H
