//
// Created by DaveRiedel on 13-Jun-22.
//

#ifndef BITSANDDROIDSCONNECTOR_INPUTTYPEENUM_H
#define BITSANDDROIDSCONNECTOR_INPUTTYPEENUM_H

static enum InputTypeEnum {
    BASICCOMMAND = 0,
    ENGINE,
    AXIS,
    SETINT = 1,
    INPUTOFF = 4,
    INPUTON = 5,
    SETCOMS = 2,
} types;

#endif //BITSANDDROIDSCONNECTOR_INPUTTYPEENUM_H
