//
// Created by DaveRiedel on 13-Jun-22.
//

#ifndef BITSANDDROIDSCONNECTOR_INPUTTYPEENUM_H
#define BITSANDDROIDSCONNECTOR_INPUTTYPEENUM_H

static enum InputTypeEnum {
    ENGINE,
    AXIS
} types;

#endif //BITSANDDROIDSCONNECTOR_INPUTTYPEENUM_H
