//
// Created by dave- on 13-7-2022.
//

#ifndef BITSANDDROIDSCONNECTOR_LOGLEVELENUM_H
#define BITSANDDROIDSCONNECTOR_LOGLEVELENUM_H
static enum LogLevel{
    DEBUG,
    WARNING,
    ERROR
},LOGLEVEL;
#endif //BITSANDDROIDSCONNECTOR_LOGLEVELENUM_H
