//
// Created by DaveRiedel on 18-8-2022.
//

#ifndef BITSANDDROIDSCONNECTOR_STYLEENUM_H
#define BITSANDDROIDSCONNECTOR_STYLEENUM_H
static enum StyleEnum {
    HEADER
} styles;
#endif //BITSANDDROIDSCONNECTOR_STYLEENUM_H
