#############################################################################
# Makefile for building: Bitsanddroidsgui
# Generated by qmake (3.1) (Qt 6.2.0)
# Project:  Bitsanddroidsgui.pro
# Template: app
# Command: C:\QtWindows\6.2.0\mingw81_64\bin\qmake.exe -o Makefile Bitsanddroidsgui.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" "CONFIG+=force_debug_info" "CONFIG+=separate_debug_info"
#############################################################################

MAKEFILE      = Makefile

EQ            = =

first: debug
install: debug-install
uninstall: debug-uninstall
QMAKE         = C:\QtWindows\6.2.0\mingw81_64\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = C:\QtWindows\6.2.0\mingw81_64\bin\qmake.exe -install qinstall
QINSTALL_PROGRAM = C:\QtWindows\6.2.0\mingw81_64\bin\qmake.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
IDC           = idc
IDL           = midl
ZIP           = zip -r -9
DEF_FILE      = 
RES_FILE      = BitsAndDroidsGui_res.o
SED           = $(QMAKE) -install sed
MOVE          = move
SUBTARGETS    =  \
		debug \
		release


debug: FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall
release: FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall

Makefile: Bitsanddroidsgui.pro ../../../../QtWindows/6.2.0/mingw81_64/mkspecs/win32-g++/qmake.conf ../../../../QtWindows/6.2.0/mingw81_64/mkspecs/features/spec_pre.prf \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/features/device_config.prf \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/common/sanitize.conf \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/common/gcc-base.conf \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/common/g++-base.conf \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/features/win32/windows_vulkan_sdk.prf \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/common/windows-vulkan.conf \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/common/g++-win32.conf \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/common/windows-desktop.conf \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/qconfig.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_ext_freetype.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_ext_libpng.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_charts.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_chartsqml.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_chartsqml_private.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_core.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_core5compat.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_core5compat_private.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_entrypoint_private.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_help.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_labsanimation.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_labsanimation_private.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_labssettings.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_labssettings_private.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_labssharedimage.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_linguist.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_linguist_private.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_network.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_openglwidgets.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_qmlcore.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_qmlcore_private.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_qmldom_private.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quickdialogs2.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quicklayouts.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_svgwidgets.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_tools_private.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_zlib_private.pri \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/features/qt_functions.prf \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/features/qt_config.prf \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/win32-g++/qmake.conf \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/features/exclusive_builds.prf \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/features/toolchain.prf \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/features/default_pre.prf \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/features/win32/default_pre.prf \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/features/resolve_config.prf \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/features/exclusive_builds_post.prf \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/features/default_post.prf \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/features/resolve_target.prf \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/features/win32/separate_debug_info.prf \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/features/qml_debug.prf \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/features/entrypoint.prf \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/features/precompile_header.prf \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/features/warn_on.prf \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/features/qt.prf \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/features/resources_functions.prf \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/features/resources.prf \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/features/moc.prf \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/features/win32/opengl.prf \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/features/uic.prf \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/features/qmake_use.prf \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/features/file_copies.prf \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/features/win32/windows.prf \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/features/testcase_targets.prf \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/features/exceptions.prf \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/features/yacc.prf \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/features/lex.prf \
		Bitsanddroidsgui.pro \
		../../../../QtWindows/6.2.0/mingw81_64/lib/Qt6PrintSupport.prl \
		../../../../QtWindows/6.2.0/mingw81_64/lib/Qt6Charts.prl \
		../../../../QtWindows/6.2.0/mingw81_64/lib/Qt6OpenGLWidgets.prl \
		../../../../QtWindows/6.2.0/mingw81_64/lib/Qt6Widgets.prl \
		../../../../QtWindows/6.2.0/mingw81_64/lib/Qt6OpenGL.prl \
		../../../../QtWindows/6.2.0/mingw81_64/lib/Qt6Gui.prl \
		../../../../QtWindows/6.2.0/mingw81_64/lib/Qt6SerialPort.prl \
		../../../../QtWindows/6.2.0/mingw81_64/lib/Qt6Network.prl \
		../../../../QtWindows/6.2.0/mingw81_64/lib/Qt6Core.prl \
		../../../../QtWindows/6.2.0/mingw81_64/lib/Qt6EntryPoint.prl \
		../../../../QtWindows/6.2.0/mingw81_64/mkspecs/features/build_pass.prf \
		Resources.qrc \
		debug/qmake_qmake_immediate.qrc \
		release/qmake_qmake_immediate.qrc
	$(QMAKE) -o Makefile Bitsanddroidsgui.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" "CONFIG+=force_debug_info" "CONFIG+=separate_debug_info"
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/features/spec_pre.prf:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/features/device_config.prf:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/common/sanitize.conf:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/common/gcc-base.conf:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/common/g++-base.conf:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/features/win32/windows_vulkan_sdk.prf:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/common/windows-vulkan.conf:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/common/g++-win32.conf:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/common/windows-desktop.conf:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/qconfig.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_ext_freetype.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_ext_libpng.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_charts.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_charts_private.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_chartsqml.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_chartsqml_private.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_core.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_core5compat.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_core5compat_private.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_core_private.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_dbus.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_designer.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_entrypoint_private.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_gui.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_help.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_help_private.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_labsanimation.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_labsanimation_private.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_labsqmlmodels.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_labssettings.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_labssettings_private.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_labssharedimage.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_labssharedimage_private.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_linguist.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_linguist_private.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_network.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_network_private.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_opengl.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_openglwidgets.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_openglwidgets_private.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_qml.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_qmlcore.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_qmlcore_private.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_qmldom_private.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_qmllocalstorage.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_qmlmodels.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_qmlmodels_private.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_qmlworkerscript.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quick.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quickdialogs2.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quickdialogs2_private.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quicklayouts.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quicklayouts_private.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_serialport.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_sql.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_svg.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_svgwidgets.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_svgwidgets_private.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_testlib.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_tools_private.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_uitools.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_widgets.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_xml.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/modules/qt_lib_zlib_private.pri:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/features/qt_functions.prf:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/features/qt_config.prf:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/win32-g++/qmake.conf:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/features/exclusive_builds.prf:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/features/toolchain.prf:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/features/default_pre.prf:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/features/win32/default_pre.prf:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/features/resolve_config.prf:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/features/exclusive_builds_post.prf:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/features/default_post.prf:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/features/resolve_target.prf:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/features/win32/separate_debug_info.prf:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/features/qml_debug.prf:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/features/entrypoint.prf:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/features/precompile_header.prf:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/features/warn_on.prf:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/features/qt.prf:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/features/resources_functions.prf:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/features/resources.prf:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/features/moc.prf:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/features/win32/opengl.prf:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/features/uic.prf:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/features/qmake_use.prf:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/features/file_copies.prf:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/features/win32/windows.prf:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/features/testcase_targets.prf:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/features/exceptions.prf:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/features/yacc.prf:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/features/lex.prf:
Bitsanddroidsgui.pro:
../../../../QtWindows/6.2.0/mingw81_64/lib/Qt6PrintSupport.prl:
../../../../QtWindows/6.2.0/mingw81_64/lib/Qt6Charts.prl:
../../../../QtWindows/6.2.0/mingw81_64/lib/Qt6OpenGLWidgets.prl:
../../../../QtWindows/6.2.0/mingw81_64/lib/Qt6Widgets.prl:
../../../../QtWindows/6.2.0/mingw81_64/lib/Qt6OpenGL.prl:
../../../../QtWindows/6.2.0/mingw81_64/lib/Qt6Gui.prl:
../../../../QtWindows/6.2.0/mingw81_64/lib/Qt6SerialPort.prl:
../../../../QtWindows/6.2.0/mingw81_64/lib/Qt6Network.prl:
../../../../QtWindows/6.2.0/mingw81_64/lib/Qt6Core.prl:
../../../../QtWindows/6.2.0/mingw81_64/lib/Qt6EntryPoint.prl:
../../../../QtWindows/6.2.0/mingw81_64/mkspecs/features/build_pass.prf:
Resources.qrc:
debug/qmake_qmake_immediate.qrc:
release/qmake_qmake_immediate.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile Bitsanddroidsgui.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" "CONFIG+=force_debug_info" "CONFIG+=separate_debug_info"

qmake_all: FORCE

make_first: debug-make_first release-make_first  FORCE
all: debug-all release-all  FORCE
clean: debug-clean release-clean  FORCE
distclean: debug-distclean release-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) "C:\Users\Dave Riedel\Documents\Bitsanddroidsgui\Bitsanddroidsgui.exe.debug" .qmake.stash

debug-mocclean:
	$(MAKE) -f $(MAKEFILE).Debug mocclean
release-mocclean:
	$(MAKE) -f $(MAKEFILE).Release mocclean
mocclean: debug-mocclean release-mocclean

debug-mocables:
	$(MAKE) -f $(MAKEFILE).Debug mocables
release-mocables:
	$(MAKE) -f $(MAKEFILE).Release mocables
mocables: debug-mocables release-mocables

check: first

benchmark: first
FORCE:

$(MAKEFILE).Debug: Makefile
$(MAKEFILE).Release: Makefile
