//
// Created by DaveRiedel on 17-8-2022.
//

#ifndef BITSANDDROIDSCONNECTOR_OUTPUTMENUBUILDER_H
#define BITSANDDROIDSCONNECTOR_OUTPUTMENUBUILDER_H


class OutputMenuBuilder {

};


#endif //BITSANDDROIDSCONNECTOR_OUTPUTMENUBUILDER_H
